### ISSUE TITLE
Hi , is this project production ready ? 

### ISSUE THREAD

**Issue by sunface** [hayk96/prometheus-api#5]
It's an awesome project, seems solved my problem: we cant configure alert rules through HTTP APIs :(

**Comment by hayk96** [comment]
Hi @sunface, thank you for your feedback! Since this project is new and not widely used, it may have a few minor gaps. It's currently in the active development stage. It's presently in the active development stage. However, the project's concept is simple, and it operates as a lightweight proxy. The supported APIs at this moment are the [following](https://github.com/hayk96/prometheus-api/tree/main/docs/rest-api#rules-api-v1).

**Comment by sunface** [comment]
thanks, got it :)
